### ISSUE TITLE
Bug: No signing request/pop-up shown

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/vortex#269] opened 2024-11-08 09:55 UTC
## Context

After a page refresh, no signing request is shown for the user. Tested on an Android phone using Chrome browser. 
The page reloaded due to a recoverable error (the signer service was not available locally) and after I fixed that, the process reached the signing stage but no signing was requested nor any error shown.
However, there is a warning 
```
'Navigation is blocked: wc:9c5dad9dbeb4eb6bbe40808d1899ed17db016bfec3bd042b9fdeb365e29136bd@2/wc?requestId=1730988197737568&sessionTopic=9abe69febffb3628afea0eecc23779de1e4c55e8ac474a8d3d4577a8df734db9'.
``` 

My flow was: Start the offramping process by clicking on the 'Confirm' button. Metamask opens and asks me to switch the network to polygon (this is expected and worked like a charm). I am back on Vortex but the process cannot continue because the signer-service is unavailable. The app starts reloading the page every 30 seconds. I make sure the signer-service is available again. I fill in the details with Mykobo and get back to the App. The signing-dialog shows after a brief delay but I don't get any notification/pop-up to open Metamask or similar.

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/f5a4263f-ee9e-4b1c-b6a1-f99f296eb837">

After waiting for ~5 minutes, the app moved to the failure stage because the request expired. 
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/a38f24ed-adc1-46d5-8bbf-2169a498d935">

## TODO

- Investigate the `Navigation is blocked` warning. This indicates that the request for signing sent by vortex via the WalletConnect implementation in rainbowkit/wagmi was blocked by the browser.

**Comment by gianfra-t** [comment] 2024-11-14 12:36
@ebma I was not able to replicate this error or my mobile. 

I tried refreshing before the request (as your experiment) and after it, and for both I see the pop-up to change to Metamask. Tried many times.

I am testing in a preview with our current [code](https://github.com/pendulum-chain/vortex/pull/278/files). Any ideas? My plan was to first replicate the error, then try appkit to see if it solved the issue.

**Comment by ebma** [comment] 2024-11-14 14:00
Hmm okay, interesting. To be fair, I think when testing stuff with rainbowkit on my phone I also never saw the exact warning 'Navigation is blocked: ...' again. So this is probably not very easy to reproduce. Has to be an edge case. One might assume that it's related to browser settings but as I also didn't really see it happen afterward, this also doesn't make too much sense.

If neither you and me are able to reproduce this issue, let's maybe close this as not planned/wont-fix and re-open the ticket if it happens again.

**Comment by gianfra-t** [comment] 2024-11-14 14:59
So you saw it only once? Or was it reported. Interesting. 
But yeah, I agree we close this for now and open it if happens more times. There is not much we can do if we can't reproduce it.

**Closed** 2024-11-14 17:26 UTC
Labels: type:bug
